### ISSUE TITLE
Need some advice

### ISSUE THREAD

**Issue by Christian-CFP** [Jason-Morcos/homebridge-magic-occupancy#11]
Hey Jason,
I'm sorry but I have no clou how this will works. Can you give me a hand?
So I will use this for e.g. as an occupancy sensor for the bathroom. There I got a hue motion sensor, a hue dimmer switch and an eve door sensor.

Give me an example how to set a sensor with your plugin. THX!

**Comment by Christian-CFP** [comment]
Ok, I see your plugin generates switches that I have to configure in HK.

**Comment by Jason-Morcos** [comment]
Sounds like you got it all figured out? :)
Don't hesitate to reach out if you have any other questions!

**Comment by Christian-CFP** [comment]
Hi, kind of. There are some questions left:

Trigger Stateless Switch
Stateful Stay-on Switches
Trigger Stay-on Switches

1. I don't get quite the difference between a Stateful Stay-on Switches and the Trigger Stay-on Switches. The do act quite the same. Maybe a example would be nice.
2. Trigger Stateless Switch: Does it trigger the delay e.g. 60sec and thats it so the lights went on and after 60sec they turn off?
3. You have this example right at the end:
"These automations add the fancy elements of turning on the hallway lights when the garage opens, keeping the hallway lights on for longer if they're already on and the kitchen lights turn on, and keeping the hallway lights on as long as the dining room lights are on (if the hallway lights are already on)"

... keeping the hallway lights on for longer if they're already on .. What does this trigger and why (for better understanding)?


But I like it so far. Thats quite the same that I am/was using with Dummy Switches.
But maybe one thing for the future. The bathroom.

I got a motion sensor in the bathroom, one in front of the bathroom (in the hallway) and one door sensor (bathroom door).
All automations like you e.g. are fine but - here it comes and I know for that it would be better to use a real occupancy sensor.

- When motion is detected in BR, occupancy is on (when not is off).
- When occupancy is on and the door is closed, Stateful Stay-on Switch is active.
- When door open Stateful Stay-on Switch is off.

So far so good. But I need some how to switch the light off when a person leaves the BR. (works just with one because no counting involved)

And this is how I have done it before.
If motion is detected in front of the BF (in the hallway) and motion is detected in BR (because if you walk out you make the motion go on) and the door is open - turn off lights. Sounds good and should work perfectly but ;)
If you close the door to early, and the sensor in the hallway does not catch you up, the lights stays on because:
- When occupancy is on and the door is closed, Stateful Stay-on Switch is active.

Any idea how to solve this?

Best

**Comment by Jason-Morcos** [comment]
> Hi, kind of. There are some questions left:
> 
> Trigger Stateless Switch Stateful Stay-on Switches Trigger Stay-on Switches
> 
> 1. I don't get quite the difference between a Stateful Stay-on Switches and the Trigger Stay-on Switches. They do act quite the same. Maybe an example would be nice.

There's some very useful info in the readme - https://github.com/Jason-Morcos/homebridge-magic-occupancy#readme
But basically there are two modes of switches:
- Stateful Switches don't turn off until you manually turn them off
- Trigger switches turn off a second or two later
Then there are two classes of switches:
- Normal Switches which generally directly control the occupancy sensor
- Stay-on switches which aren't important enough to enable the occupancy sensor, but if the occupancy sensor is already enabled they can preserve occupancy
- 
> 2. Trigger Stateless Switch: Does it trigger the delay e.g. 60sec and thats it so the lights went on and after 60sec they turn off?
- Not quite, if the switch is in the process of the delay _already_ it resets the delay back to the initial number (60). Think of it is a trigger that says at that second the room should still be occupied. If the delay isn't yet running, the trigger switch doesn't do anything. A good example of a trigger switch might be an automation for a garage door - you want the lights to turn on when the garage door opens but you don't want the lights to stay on as long as the garage door is open - so you use a trigger switch to set that there's occupancy but the garage doesn't keep the lights on longer than the delay (but other switches could).

> 3. You have this example:
>    "The other two types of simple switches, Stateful and Trigger Stay-on Switches, act just like their non Stay-on siblings with one key difference - they can't activate the occupation sensor, only keep it active. These are useful, for example, if you have a hallway light that you want to turn on when the garage opens and keep on then as long as you have motion anywhere in the house (but you wouldn't want motion in the house to normally turn the light on)."
> 
> ... when the garage opens and keep on then as long as you have motion anywhere in the house .. What does this trigger and why (for better understanding)?
- When garage opens, turn on trigger switch. This instantly starts occupancy, but because it's a trigger switch and there's no other switches on the delay timer starts.
- For all the motion sensors in the house, hook them up with stay-on only switches that are turned on and off by motion starting and stopping respectively. Because these are stay-on type switches, they won't normally start occupancy, but if occupancy is already started (ie via the garage open trigger switch) they can keep occupancy going as long as they're on. 
- What this lets you do, is get home with groceries and walk up and down and up and down and the lights stay on until you stop walking up and down.

> 
> But I like it so far. Thats quite the same how I am/was using this with Dummy Switches. But maybe one thing for the future. The bathroom.
> 
> I got a motion sensor in the bathroom, one in front of the bathroom (in the hallway) and one door sensor (bathroom door). All automations like your e.g. are fine but - here it comes and I know for that it would be better to use a real occupancy sensor.
> 
> * When motion is detected in BR, occupancy is on (when not is off).
> * When occupancy is on and the door is closed, Stateful Stay-on Switch is active.
> * When door open Stateful Stay-on Switch is off.
> 
> So far so good. But I need some how to switch the light off when a person leaves the BR. I do not want to wait the delay of 60sec. (or less) I want them to go off imediatly. (works just with one because no counting involved)
> 
> And this is how I have done it before. If motion is detected in front of the BR (in the hallway) and motion is detected in BR (because if you walk out you make the motion go off) and the door is open - turn off lights or in this case your "Light Switch". Sounds good and should work perfectly but ;) If you close the door to early, and the sensor in the hallway does not catch you up, the lights stays on because:
> 
> * When occupancy is on and the door is closed, Stateful Stay-on Switch is active.
> 
> Any idea how to solve this?
I would try using a master shutoff here! Master shutoff should instantly turn off the light and all switches.

> 
> Best

Happy automating!

**Comment by Christian-CFP** [comment]
Ok, got it now with the Trigger Switches! Thank you!!!
